# Generated by Django 5.0.6 on 2024-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polera',
            fields=[
                ('id_polera', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=1)),
                ('precio', models.CharField(max_length=6)),
            ],
        ),
    ]
